FROM nginx:alpine

# Remove any existing config files
RUN rm /etc/nginx/conf.d/*

# Copy config files
# *.conf files in "conf.d/" dir get included in main config
COPY ./conf.d /etc/nginx/conf.d/

# Launch NGINX
CMD [ "nginx", "-g", "daemon off;" ]

EXPOSE 80 443
