name: bomsbro-blog-webapp

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # CHECK OUT TO $GITHUB_WORKSPACE
      - uses: actions/checkout@v3
          
      # DOCKER HUB
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
          
      # BUILD IMAGE
      - name: Compose Images
        run: 
          docker-compose up -d --build
          
      # PUSH IMAGE
      - name: release to DockerHub
        env:
          NAME: bomsbro # 계정 명
          REPO: bomsbro-blog-web-app # 레포 이름
        run: 
          docker tag $REPO:latest $NAME/$REPO:latest
          docker push $NAME/$REPO:latest      
