name: bomsbro-blog-webapp

on:
  push:
    branches: [ "master" ]
    
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      # CHECK OUT TO $GITHUB_WORKSPACE
      - name: Check out
        uses: actions/checkout@v3
        
      # BUILD IMAGE
      - name: Compose Images
        run: 
          docker-compose up -d --build
          
      # PULL AND LEARN IMAGE ON INSTANCE SSH
      - name: Deploy Images
        run: bash ${GITHUB_WORKSPACE}/bomsbro-blog-web-app-deploy.sh 
          ${{secrets.REMOTE_HOST}} 
          ${{secrets.REMOTE_SSH_PORT}} 
          ${{secrets.REMOTE_USERNAME}} 
          ${{secrets.REMOTE_PASSWORD}}
          'bomsbro-blog-web-app_nextjs'
          
      # DOCKER HUB
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
          
      # BACKUP IMAGE
      - name: release to DockerHub
        env:
          NAME: bomsbro # 계정 명
          REPO: bomsbro-blog-web-app # 레포 이름
        run: 
          docker tag $REPO:latest $NAME/$REPO:latest
          docker push $NAME/$REPO:latest      
