name: bomsbro-blog-webapp

on:
  push:
    branches: [ "master" ]
    
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      # CHECK OUT TO $GITHUB_WORKSPACE
      - name: Check out
        uses: actions/checkout@v3
        
      # BUILD IMAGE
      - name: Compose Images
        run: 
          docker-compose up -d --build
          
      # PULL AND LEARN IMAGE ON INSTANCE SSH
      - name: Deploy Proxy
        run: bash ${GITHUB_WORKSPACE}/scripts/bomsbro-blog-web-app-nginx-deploy.sh 
          ${{secrets.REMOTE_HOST}} 
          ${{secrets.REMOTE_SSH_PORT}} 
          ${{secrets.REMOTE_USERNAME}} 
          ${{secrets.REMOTE_PASSWORD}}
          'bomsbro-blog-web-app_nginx'

      - name: Deploy Webapp
        run: bash ${GITHUB_WORKSPACE}/scripts/bomsbro-blog-web-app-nextjs-deploy.sh 
          ${{secrets.REMOTE_HOST}} 
          ${{secrets.REMOTE_SSH_PORT}} 
          ${{secrets.REMOTE_USERNAME}} 
          ${{secrets.REMOTE_PASSWORD}}
          'bomsbro-blog-web-app_nextjs'

      # Clean Up Images
      - name: Prune Images
        run:  sshpass -p $REMOTE_PASSWORD ssh -p $REMOTE_SSH_PORT $REMOTE_USERNAME@$REMOTE_HOST -o StrictHostKeyChecking=no 'docker image prune'

      # DOCKER HUB
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
          
      # BACKUP IMAGE
      - name: release to DockerHub
        env:
          NAME: bomsbro # 계정 명
          REPO: bomsbro-blog-web-app # 레포 이름
        run: 
          docker tag $REPO:latest $NAME/$REPO:latest
          docker push $NAME/$REPO:latest      
