name: bomsbro-blog-api

on:
  push:
    branches: [ "master" ]
    
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      # CHECK OUT TO $GITHUB_WORKSPACE
      - name: Check out
        uses: actions/checkout@v3
        
      # BUILD IMAGE
      - name: Compose Images
        run: 
          docker-compose up -d --build
          
      # SAVE AND RUN IMAGE ON INSTANCE
      - name: Deploy API
        run: bash ${GITHUB_WORKSPACE}/scripts/bomsbro-blog-api-deploy.sh 
          ${{secrets.REMOTE_HOST}} 
          ${{secrets.REMOTE_SSH_PORT}} 
          ${{secrets.REMOTE_USERNAME}} 
          ${{secrets.REMOTE_PASSWORD}}
          'bomsbro-blog-api'

      # CLEANUP IMAGES ON INSTANCE
      - name: Prune Images
        run:  sshpass -p $REMOTE_PASSWORD ssh -p $REMOTE_SSH_PORT $REMOTE_USERNAME@$REMOTE_HOST -o StrictHostKeyChecking=no 'docker image prune'

      # DOCKER HUB
      - name: Sign in
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
          
      # BACKUP IMAGE
      - name: Release Images
        env:
          NAME: bomsbro # 계정 명
          REPO: bomsbro-blog-api # 레포 이름
        run: 
          docker tag $REPO:latest $NAME/$REPO:latest
          docker push $NAME/$REPO:latest      
